#!/usr/bin/env python3
"""
Build the chip-level native-element LVS reference netlist
(adc_top/layout/refs/adc_top_ref.spice) for INT-8 / Gate 5, from the
already-LVS-proven block references:

  sar_logic/layout/refs/sar_logic_ref.spice  (leaf + DFF + sar_logic
      subckts, hierarchical native M elements -- SAR-6 sign-off)
  comparator/schematic/strongarm.spice       (native M elements, the
      COMP-10 netlist-diff-verified schematic netlist)
  dac/layout/dac_top_ref.spice               (flat native M/C elements,
      the DAC Gate-5 sign-off reference; ground = schematic global "0")
  adc_glue instances (verbatim from adc_top/sim/adc_top_subckt.spice,
      reusing the SAR leaf subckts)

DAC transformation (mechanical, no device edits): the chip has a single
VSS net that includes the DAC's internal ground, so the DAC subckt copy
gets a VSS port appended and every standalone node token "0" in its
body replaced by VSS. Parameter tokens all contain '=' and never equal
a bare "0", so a token-wise replacement is exact.

Native M/C elements are MANDATORY on every device card: an X-call to an
undefined subckt silently extracts 0 devices = false pass (see
run_dac_lvs.sh header).

Top wiring is pin_contracts.md section 3 / adc_top_subckt.spice:
  x_dac  VIN<-VSS (reset reference), B_i <- BIT_i, DAC_TOP -> x_cmp VIN2
  x_cmp  VIN1 <- chip VIN, CK <- glue, VOUT1/2 -> glue latch
  x_sar  CMP_OUT <- glue latch Q
Expected device total: 377 (DAC) + 11 (comparator) + 458 (SAR) + 16
(glue) = 862 MOS+caps.
"""

import re

BASE = "/foss/designs"
OUT = BASE + "/adc_top/layout/refs/adc_top_ref.spice"


def read(path):
    with open(path) as f:
        return f.read()


def transform_dac(text):
    lines = []
    in_sub = False
    for ln in text.splitlines():
        s = ln.strip()
        if s.lower().startswith(".subckt dac_top_floorplan"):
            in_sub = True
            lines.append(s + " VSS")
            continue
        if s.lower().startswith(".ends"):
            in_sub = False
            lines.append(ln)
            continue
        if in_sub and s and not s.startswith("*"):
            toks = ln.split()
            toks = ["VSS" if (t == "0" and "=" not in t) else t for t in toks]
            lines.append(" ".join(toks))
        elif not s.startswith("*"):
            lines.append(ln)
    return "\n".join(ln for ln in lines if ln.strip())


def main():
    sar = read(BASE + "/sar_logic/layout/refs/sar_logic_ref.spice")
    sar = "\n".join(ln for ln in sar.splitlines()
                    if not ln.strip().startswith("*"))
    cmp_ = read(BASE + "/comparator/schematic/strongarm.spice")
    cmp_ = "\n".join(ln for ln in cmp_.splitlines()
                     if not ln.strip().startswith("*") and ln.strip())
    dac = transform_dac(read(BASE + "/dac/layout/dac_top_ref.spice"))

    glue = """.subckt adc_glue CLK CK RST_N SAMPLE VOUT1 VOUT2 CMP_OUT VDD VSS
x_inv_ck VDD CLK CK VSS inv
x_inv_smp VDD RST_N SAMPLE VSS inv
x_ib1 VDD VOUT1 V1B VSS inv
x_ib2 VDD VOUT2 V2B VSS inv
x_nq VDD V2B QB CMP_OUT VSS nor2
x_nqb VDD V1B CMP_OUT QB VSS nor2
.ends"""

    top = """.subckt adc_top VDD VSS VIN CLK RST_N BIT_7 BIT_6 BIT_5 BIT_4 BIT_3 BIT_2 BIT_1 BIT_0 EOC
x_dac VSS VDD SAMPLE BIT_0 BIT_1 BIT_2 BIT_3 BIT_4 BIT_5 BIT_6 BIT_7 DAC_TOP VSS dac_top_floorplan
x_cmp VDD CK VOUT2 VOUT1 VIN DAC_TOP VSS strongarm
x_sar VDD VSS BIT_7 BIT_6 BIT_5 BIT_4 BIT_3 BIT_2 BIT_1 BIT_0 EOC RST_N CMP_OUT CLK sar_logic
x_glue CLK CK RST_N SAMPLE VOUT1 VOUT2 CMP_OUT VDD VSS adc_glue
.ends"""

    hdr = ("* Chip-level native-element LVS reference for adc_top "
           "(INT-8 / Gate 5).\n* GENERATED by designs/scripts/"
           "gen_adc_chip_ref.py -- do not hand-edit.\n"
           "* 377 DAC + 11 comparator + 458 SAR + 16 glue = 862 devices.\n")
    body = "\n".join((hdr, sar, cmp_, dac, glue, top)) + "\n"
    with open(OUT, "w") as f:
        f.write(body)
    n_m = len(re.findall(r"(?im)^M\S*\s", body))
    n_c = len(re.findall(r"(?im)^C\S*\s", body))
    print("wrote %s: %d M cards, %d C cards (in subckt defs)" % (OUT, n_m, n_c))


if __name__ == "__main__":
    main()
